### Loading the trained CNN

In [17]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Dropout
from keras.layers import Conv2D,MaxPooling2D

data = np.load('dataChestXray.npy')
target = np.load('targetChestXray.npy')

def loadingCNN():
    model = Sequential()

    model.add(Conv2D(32,(3,3),input_shape = data.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size = (2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(32,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size = (2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(64,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size = (2,2)))
    model.add(Dropout(0.5))

    model.add(Flatten())

    model.add(Dense(128,activation = 'relu'))
    model.add(Dropout(0.5))
    model.add(Dense(2,activation = 'softmax'))

    model.compile(loss = 'categorical_crossentropy',optimizer = 'adam',metrics = ['accuracy'])
    model.load_weights('Pnemonia_predictions_using_chest_xray_99.20.h5')
    return model

loadingCNN()

<Sequential name=sequential_14, built=True>

### Preprocessing the images to test & testing the model

In [18]:
import cv2 as cv
import os
  
testPath = 'Testimages'
imageNames = os.listdir(testPath)
model = loadingCNN()
category = {0:'Normal',1:'Pnemonia'}

fixed_size = (800, 600)
cv.namedWindow('LIVE', cv.WINDOW_NORMAL)
cv.resizeWindow('LIVE', fixed_size[0], fixed_size[1])

for imageName in imageNames:
    imagePath = os.path.join(testPath,imageName)
    image = cv.imread(imagePath)
    grayImage = cv.cvtColor(image,cv.COLOR_BGR2GRAY)
    resized = cv.resize(grayImage,(128,128))
    normalized = resized/255
    reshaped = np.reshape(normalized,(1,128,128,1))
    
    result = model.predict(reshaped)
    label = np.argmax(result,axis=1)[0]
    prob = np.max(result,axis=1)[0]
    prob = round(prob,2)*100
    
    displayImage = cv.resize(image, fixed_size)

    cv.putText(displayImage, str(category[label]), (50, 50), cv.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2)
    cv.putText(displayImage, f'{prob:.0f}%', (50, 100), cv.FONT_HERSHEY_SIMPLEX, 1.5, (255, 255, 255), 2) # Displaying accuracy on the image

    cv.imshow('LIVE', displayImage)
    key = cv.waitKey(3000)

    if key == 27:  # If the 'ESC' key is pressed, exit the loop
        break
    
    print(result)

cv.destroyAllWindows()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step
[[0.22020441 0.7797956 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step
[[0.21754868 0.78245133]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.23551297 0.76448697]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[0.23219109 0.7678089 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[0.21624608 0.7837539 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.22034824 0.77965176]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[[0.21813115 0.7818688 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step
[[0.219982 0.780018]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[0.22185054 0.7781494 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[0.21452186 0.7854781 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.23648843 0.7635116 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[0.22920537 0.77079463]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.21796912 0.78203094]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[0.23185351 0.76814646]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step
[[0.23220034 0.7677996 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[0.22