### Loading the trained CNN

In [3]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Activation,Flatten,Dropout
from keras.layers import Conv2D,MaxPooling2D

data=np.load('dataChestXray.npy')
target=np.load('targetChestXray.npy')

def loadingCNN():
    model=Sequential()

    model.add(Conv2D(32,(3,3),input_shape=data.shape[1:]))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(32,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Conv2D(64,(3,3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(0.5))

    model.add(Flatten())

    model.add(Dense(128,activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(2,activation='softmax'))

    model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
    model.load_weights('Pnemonia_predictions_using_chest_xray_99.20.keras')
    return model

loadingCNN()

<Sequential name=sequential_2, built=True>

### Preprocessing the images to test&testing the model

In [4]:
import cv2 as cv
import os
  
testPath='Testimages'
imageNames=os.listdir(testPath)
model=loadingCNN()
category={0:'Normal',1:'Pnemonia'}

for imageName in imageNames:
    imagePath=os.path.join(testPath,imageName)
    image=cv.imread(imagePath)
    grayImage=cv.cvtColor(image,cv.COLOR_BGR2GRAY)
    resized=cv.resize(grayImage,(128,128))
    normalized=resized/255
    reshaped=np.reshape(normalized,(1,128,128,1))
    result=model.predict(reshaped)
    label=np.argmax(result,axis=1)[0]
    prob=np.max(result,axis=1)[0]
    prob=round(prob,2)*100
#image[:50,:]=[0,255,0]
    cv.putText(image,str(category[label]),(100,100),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
#     accuracy 
#     cv.putText(image,str(prob),(100,200),cv.FONT_HERSHEY_SIMPLEX,3,(255,255,255),2)
    cv.imshow('LIVE',image)
    cv.waitKey(5000)
    print(result)
#     print("="*20)
#     print(result)    

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 239ms/step
[[0.38885033 0.6111496 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step
[[0.2895105 0.7104896]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[0.619117   0.38088295]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
[[0.22127308 0.7787269 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.13203402 0.86796594]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
[[0.50218153 0.4978184 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
[[0.43107587 0.56892407]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[0.7648795  0.23512045]]
